services:
  postgres:
    image: postgres:15
    container_name: postgresql_db
    environment:
      POSTGRES_DB: calculator_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"